# Generated by Django 5.0.3 on 2024-03-26 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
