# Generated by Django 4.2.6 on 2023-12-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_aimessage_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
