# Generated by Django 4.2.6 on 2023-12-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='day',
            new_name='day_time',
        ),
    ]
