# Generated by Django 4.2.6 on 2023-12-23 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assets',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
