# Generated by Django 5.0 on 2024-01-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_board_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
